# application.yml
spring:
  datasource:
    url: jdbc:mysql://mysql.training:3306/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: choerodon

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://register-server.training:8000/eureka/
    registryFetchIntervalSeconds: 10

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true

me:
    number: 20611
    name: 周廷宇